#!/bin/bash
# lore post-commit hook
# Appends each commit to lore/CHANGELOG.md automatically.
# Install: copy to .git/hooks/post-commit and chmod +x

LORE_DIR="$(git rev-parse --show-toplevel)/lore"
CHANGELOG="$LORE_DIR/CHANGELOG.md"

# Only run if lore/ exists in this repo
if [ ! -d "$LORE_DIR" ]; then
  exit 0
fi

HASH=$(git rev-parse --short HEAD)
DATE=$(date "+%Y-%m-%d %H:%M")
SUBJECT=$(git log -1 --format="%s")
BODY=$(git log -1 --format="%b")

# Create CHANGELOG.md with header if it doesn't exist
if [ ! -f "$CHANGELOG" ]; then
  echo "# Changelog" > "$CHANGELOG"
  echo "" >> "$CHANGELOG"
  echo "_Auto-generated by lore post-commit hook. Do not edit manually._" >> "$CHANGELOG"
  echo "" >> "$CHANGELOG"
fi

# Append the new entry
{
  echo "## $DATE — $HASH — $SUBJECT"
  if [ -n "$BODY" ]; then
    echo ""
    echo "$BODY"
  fi
  echo ""
  echo "---"
  echo ""
} >> "$CHANGELOG"
